name = "Testpack"
author = "Loewetiger"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50c5b8924890b2e5f57f8e2ba2fd330d43a01997acde3b1016e8d5823178f3f9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
