name = "Testpack"
author = "Loewetiger"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00d3b0c723867f3a950772dcb62444fcc5f5e98b815b6c7242acf6c7732f909d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.132"
