name = "Testpack"
author = "Loewetiger"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bde26cd8acf79b237560a65b5d27bb2c938eeb71731302a8cda2fec0e4eff289"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.132"
